import Head from "next/head";
import { SpotifyAuth } from 'react-spotify-auth'
import 'react-spotify-auth/dist/index.css'

export default function Home (){
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SpotifyAuth
          redirectUri={`${globalThis?.location?.href}callback`}
          clientID='888604926f67422cbc81a4ba0daf142d'
          scopes={['user-top-read']}
        />
    </>
  );
}
